import {auth, db} from "../firebase-config.js";
import {onAuthStateChanged, signOut, deleteUser, reauthenticateWithCredential, EmailAuthProvider, GoogleAuthProvider, reauthenticateWithPopup} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import {doc, deleteDoc} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const $=s=>document.querySelector(s);
const key=(uid,n)=>`zad_${n}_${uid}`;
let currentUser=null;
function render(user){const name=user.displayName||user.email?.split("@")[0]||"الطالب";$("#studentName").textContent=name;const fav=JSON.parse(localStorage.getItem(key(user.uid,"favorites"))||"[]");const read=JSON.parse(localStorage.getItem(key(user.uid,"read"))||"[]");$("#favCount").textContent=fav.length;$("#readCount").textContent=read.length;const total=Math.max(fav.length+read.length,1);$("#progress").textContent=Math.min(100,Math.round(read.length/total*100))+"%";if(fav.length)$("#favorites").innerHTML=fav.map(x=>`<div class="item"><span>${x}</span><small>مفضل</small></div>`).join("");if(read.length)$("#reading").innerHTML=read.map(x=>`<div class="item"><span>${x}</span><small>مقروء</small></div>`).join("");const notices=JSON.parse(localStorage.getItem("zad_announcements")||"[]");$("#announcements").innerHTML=(notices.length?notices:[{title:"مرحبًا بك في زاد المعرفة",text:"تابع المكتبة باستمرار لمعرفة الكتب والإعلانات الجديدة."}]).map(n=>`<div class="notice"><b>${n.title}</b><span>${n.text}</span></div>`).join("")}
async function recentAuth(user){const provider=user.providerData?.[0]?.providerId||"";if(provider==="password"){const password=prompt("لأمان حسابك، اكتب كلمة المرور لتأكيد حذف الحساب:");if(!password)throw new Error("cancelled");await reauthenticateWithCredential(user,EmailAuthProvider.credential(user.email,password));}else{await reauthenticateWithPopup(user,new GoogleAuthProvider());}}
async function deleteAccount(){if(!currentUser)return;const ok=confirm("حذف الحساب نهائيًا؟ سيتم حذف بيانات الحساب ولا يمكن التراجع.");if(!ok)return;if(prompt('للتأكيد اكتب: حذف الحساب')!=="حذف الحساب")return;const btn=$("#deleteAccount");btn.disabled=true;btn.textContent="جارٍ حذف الحساب…";try{await recentAuth(currentUser);await deleteDoc(doc(db,"users",currentUser.uid));localStorage.removeItem(key(currentUser.uid,"favorites"));localStorage.removeItem(key(currentUser.uid,"read"));await deleteUser(currentUser);alert("تم حذف الحساب نهائيًا.");location.replace("../login/index.html");}catch(error){console.error("Delete account error:",error);if(error.message==="cancelled"){alert("تم إلغاء الحذف.");}else if(error.code==="auth/wrong-password"){alert("كلمة المرور غير صحيحة.");}else if(error.code==="auth/popup-closed-by-user"){alert("تم إغلاق نافذة إعادة التحقق.");}else{alert(`تعذر حذف الحساب. رمز الخطأ: ${error.code||"unknown"}`);}btn.disabled=false;btn.textContent="حذف الحساب";}}
onAuthStateChanged(auth,user=>{if(!user){location.replace("../login/index.html");return}currentUser=user;render(user)});$("#logout").onclick=()=>signOut(auth).then(()=>location.replace("../login/index.html"));$("#deleteAccount")?.addEventListener("click",deleteAccount);